#!/usr/bin/env bash
# Copyright AlpineReplay Inc, 2026. All rights reserved.
# Author: Leo Khramov
#
# Idempotent installer for the review orchestrator.
#
# Default mode wires up:
#   - ~/.config/review-orchestrator/config.json (with a generated authToken)
#   - ~/.config/review-orchestrator/mcp-headers.sh
#   - ~/.claude/hooks/stop-review.mjs
#   - the mcpServers.review entry in ~/.claude.json
#   - the Stop hook entry in ~/.claude/settings.json
#   - the review-orchestrator block in ~/.claude/CLAUDE.md
#
# Pass --launch to also drop the launchd plist into
# ~/Library/LaunchAgents and bootstrap it as a background agent.
#
# Every step is idempotent: rerunning produces no change unless source
# bytes have actually drifted, and backups are written to
# <path>.bak.<utc-ts> only when bytes change.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd -P)"

LAUNCH=0
DRY_RUN=0
HOME_DIR="${HOME:-}"

usage() {
    cat <<'EOF'
Usage: ./install.sh [--launch] [--dry-run] [--home <dir>] [--help]

  --launch     Also install the launchd plist in ~/Library/LaunchAgents
               and bootstrap the daemon. Without this, the daemon must
               be started manually (npm start) for the MCP entry and
               Stop hook to do anything.
  --dry-run    Print what would happen without writing.
  --home DIR   Install into DIR/.config and DIR/.claude instead of $HOME.
               Primarily for the test harness.
  --help, -h   Show this help.

Idempotent: rerun any time. Existing authToken is preserved.
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --launch) LAUNCH=1; shift ;;
        --dry-run) DRY_RUN=1; shift ;;
        --home)
            shift
            [ $# -gt 0 ] || { echo "--home needs a value" >&2; exit 1; }
            HOME_DIR="$1"; shift ;;
        --help|-h) usage; exit 0 ;;
        *) echo "unknown arg: $1" >&2; usage; exit 1 ;;
    esac
done

if [ -z "$HOME_DIR" ]; then
    echo "HOME is empty and --home not supplied" >&2
    exit 1
fi
HOME_DIR="$(cd "$HOME_DIR" && pwd -P)"

CONFIG_DIR="$HOME_DIR/.config/review-orchestrator"
CONFIG_PATH="$CONFIG_DIR/config.json"
HEADERS_SCRIPT="$CONFIG_DIR/mcp-headers.sh"
CLAUDE_DIR="$HOME_DIR/.claude"
HOOKS_DIR="$CLAUDE_DIR/hooks"
HOOK_PATH="$HOOKS_DIR/stop-review.mjs"
CLAUDE_JSON="$HOME_DIR/.claude.json"
SETTINGS_JSON="$CLAUDE_DIR/settings.json"
CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"
LAUNCHAGENTS_DIR="$HOME_DIR/Library/LaunchAgents"
PLIST_NAME="com.leo.review-orchestrator.plist"
PLIST_DST="$LAUNCHAGENTS_DIR/$PLIST_NAME"
PLIST_SRC="$REPO_ROOT/launchd/$PLIST_NAME"

SUMMARY=()

note() { SUMMARY+=("$1"); }

# Echo what we'd do under --dry-run; do nothing.
maybe() {
    if [ "$DRY_RUN" -eq 1 ]; then
        echo "[dry-run] $*"
        return 1
    fi
    return 0
}

# Compare bytes; install only if differ. Reports "installed" when the
# destination did not exist beforehand, "updated" when bytes drifted.
install_file_idempotent() {
    local src="$1"
    local dst="$2"
    local mode="$3"
    local label="$4"
    if [ -f "$dst" ] && cmp -s "$src" "$dst"; then
        note "  unchanged: $label ($dst)"
        return 0
    fi
    local existed=0
    [ -f "$dst" ] && existed=1
    if ! maybe "install file: $src → $dst (mode $mode)"; then return 0; fi
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    chmod "$mode" "$dst"
    if [ "$existed" -eq 1 ]; then
        note "  updated:   $label ($dst)"
    else
        note "  installed: $label ($dst)"
    fi
}

# Write mcp-headers.sh from a heredoc — content is deterministic.
write_headers_script() {
    local target="$1"
    local config="$2"
    local tmp; tmp="$(mktemp)"
    cat > "$tmp" <<HEADERS
#!/usr/bin/env bash
# Auto-generated by review-orchestrator install.sh. Do not edit.
set -euo pipefail
config="$config"
node --input-type=module -e '
  import { readFileSync } from "node:fs"
  const cfg = JSON.parse(readFileSync(process.argv[1], "utf8"))
  process.stdout.write(JSON.stringify({ "X-Review-Token": cfg.authToken }))
' "\$config"
HEADERS
    if [ -f "$target" ] && cmp -s "$tmp" "$target"; then
        rm -f "$tmp"
        note "  unchanged: mcp-headers.sh ($target)"
        return 0
    fi
    if ! maybe "write headers script: $target"; then
        rm -f "$tmp"
        return 0
    fi
    mkdir -p "$(dirname "$target")"
    mv "$tmp" "$target"
    chmod 0700 "$target"
    note "  installed: mcp-headers.sh ($target)"
}

# Render the launchd plist via the Node helper. Done in JS so that
# paths containing `&` or `|` cannot corrupt the substitution (they would
# under raw sed). Returns:
#   0 = wrote new/updated plist
#   1 = unchanged on disk (no signal needed)
#   2 = dry-run skip
render_plist() {
    local src="$1"
    local dst="$2"
    local node_bin="$3"
    local repo_root="$4"
    local home="$5"
    if ! maybe "render plist: $src → $dst"; then return 2; fi
    mkdir -p "$(dirname "$dst")"
    local out
    if ! out="$(node "$REPO_ROOT/install/render-plist.mjs" \
            "$src" "$dst" "$node_bin" "$repo_root" "$home" 2>&1)"; then
        echo "install: render-plist failed: $out" >&2
        exit 1
    fi
    local action="${out%%:*}"
    note "  $action: launchd plist ($dst)"
    if [ "$action" = "unchanged" ]; then return 1; fi
    return 0
}

# Run a Node install helper; capture its single-line status output and
# fold it into SUMMARY.
run_helper() {
    local label="$1"; shift
    local script="$1"; shift
    if ! maybe "run helper: $label"; then return 0; fi
    local out
    out="$(node "$script" "$@")" || {
        echo "install: helper $label failed: $out" >&2
        exit 1
    }
    # Helper output is "action:path".
    local action="${out%%:*}"
    local path_part="${out#*:}"
    note "  $action: $label ($path_part)"
}

echo "review-orchestrator install"
echo "  REPO_ROOT: $REPO_ROOT"
echo "  HOME:      $HOME_DIR"
echo "  --launch:  $([ "$LAUNCH" -eq 1 ] && echo yes || echo no)"
echo "  --dry-run: $([ "$DRY_RUN" -eq 1 ] && echo yes || echo no)"
echo

# 1. authToken + config.json
run_helper "config.json" "$REPO_ROOT/install/ensure-token.mjs" "$CONFIG_PATH" "$HOME_DIR"

# 2. mcp-headers.sh
write_headers_script "$HEADERS_SCRIPT" "$CONFIG_PATH"

# 3. Stop hook
install_file_idempotent "$REPO_ROOT/hooks/stop-review.mjs" "$HOOK_PATH" 0700 "Stop hook"

# 4a. Read the actual port/bind out of the config so the MCP URL we wire
# into ~/.claude.json (and the /healthz probe under --launch) point at the
# daemon the user actually configured. clientHost is the form to use in
# URLs: wildcard binds normalized to loopback, IPv6 bracketed.
PORT=7777
BIND="127.0.0.1"
CLIENT_HOST="127.0.0.1"
if [ -f "$CONFIG_PATH" ]; then
    if ! ENDPOINT="$(node "$REPO_ROOT/install/read-config-endpoint.mjs" "$CONFIG_PATH")"; then
        echo "install: failed to read endpoint from $CONFIG_PATH" >&2
        exit 1
    fi
    # ENDPOINT is "port\tbind\tclientHost".
    PORT="${ENDPOINT%%	*}"
    REST="${ENDPOINT#*	}"
    BIND="${REST%%	*}"
    CLIENT_HOST="${REST#*	}"
    CLIENT_HOST="${CLIENT_HOST%$'\n'}"
fi
echo "  endpoint:  $BIND:$PORT (client URL host: $CLIENT_HOST)"

# 4b. mcp entry in ~/.claude.json — pass the resolved port/bind so the
# entry matches the daemon's actual address.
run_helper "~/.claude.json (MCP entry)" "$REPO_ROOT/install/merge-mcp.mjs" \
    "$CLAUDE_JSON" "$HEADERS_SCRIPT" "$PORT" "$CLIENT_HOST"

# 5. Stop hook entry in ~/.claude/settings.json
run_helper "~/.claude/settings.json (Stop hook)" "$REPO_ROOT/install/merge-stop-hook.mjs" "$SETTINGS_JSON" "$HOOK_PATH"

# 6. claude-md-snippet.md into ~/.claude/CLAUDE.md
run_helper "~/.claude/CLAUDE.md (snippet)" "$REPO_ROOT/install/merge-claude-md.mjs" "$CLAUDE_MD" "$REPO_ROOT/claude-md-snippet.md"

# 7. (optional) launchd
if [ "$LAUNCH" -eq 1 ]; then
    NODE_BIN="$(command -v node)"
    if [ -z "$NODE_BIN" ]; then
        echo "install: node not on PATH; cannot install launchd plist" >&2
        exit 1
    fi

    # The plist points its StandardOut/StandardErr at ~/.claude/logs/.
    # launchd refuses to start the agent if that directory doesn't
    # already exist, so create it before bootstrapping.
    LOGS_DIR="$HOME_DIR/.claude/logs"
    if ! maybe "mkdir $LOGS_DIR"; then
        :
    else
        mkdir -p "$LOGS_DIR"
    fi

    render_plist "$PLIST_SRC" "$PLIST_DST" "$NODE_BIN" "$REPO_ROOT" "$HOME_DIR" || true

    if ! maybe "launchctl bootstrap"; then
        :
    else
        DOMAIN="gui/$(id -u)"
        # Bootout if already loaded (idempotent rerun); ignore failure.
        launchctl bootout "$DOMAIN/com.leo.review-orchestrator" 2>/dev/null || true
        if ! launchctl bootstrap "$DOMAIN" "$PLIST_DST"; then
            echo "install: launchctl bootstrap failed for $PLIST_DST" >&2
            echo "  Try: launchctl bootstrap $DOMAIN $PLIST_DST" >&2
            echo "  Check: tail -n 50 $LOGS_DIR/review-server.err.log" >&2
            exit 1
        fi

        # Probe /healthz to confirm the daemon actually came up. Retry
        # for ~10s with a short backoff — launchd may take a moment to
        # spawn node.
        HEALTH_URL="http://${CLIENT_HOST}:${PORT}/healthz"
        echo "  waiting:   ${HEALTH_URL}"
        OK=0
        for i in 1 2 3 4 5 6 7 8 9 10; do
            if curl -sf --max-time 1 "$HEALTH_URL" >/dev/null 2>&1; then
                OK=1
                break
            fi
            sleep 1
        done
        if [ "$OK" -ne 1 ]; then
            echo "install: bootstrap succeeded but /healthz never returned 200 at $HEALTH_URL" >&2
            echo "  Check: tail -n 50 $LOGS_DIR/review-server.err.log" >&2
            exit 1
        fi
        note "  launched:  launchd agent $DOMAIN/com.leo.review-orchestrator (verified via /healthz)"
    fi
else
    note "  skipped:   launchd plist (--launch not passed; daemon must be started manually with \`npm start\`)"
fi

echo
echo "Summary:"
# `${SUMMARY[@]+...}` keeps `set -u` happy when SUMMARY is empty (dry-run).
for line in ${SUMMARY[@]+"${SUMMARY[@]}"}; do
    printf '%s\n' "$line"
done
echo

if [ "$LAUNCH" -eq 0 ]; then
    echo "review-orchestrator: install complete."
    echo "Start the daemon now with:  (cd $REPO_ROOT && npm start)"
else
    echo "review-orchestrator: install complete (launchd agent installed)."
fi
